### ISSUE TITLE
ironically, the SSL certificate has expired on crypto101.io

### ISSUE THREAD

**Issue by thedavidmeister** [crypto101/crypto101.github.io#1]
https://www.evernote.com/shard/s18/sh/f01e0e9b-f0e2-48df-a9a1-9969fbe155db/9eb4d3eb0e783429b057f532ac3da625

**Comment by lvh** [comment]
Thanks! Alas, I am painfully aware. I was hoping to just redirect to crypto101.github.io, but then HSTS happened.

**Comment by lvh** [comment]
Could you check if crypto101.github.io works for you?

**Comment by lvh** [comment]
Should be fixed now; please reopen if it isn't.
