### ISSUE TITLE
Missing HSTS redirection

### ISSUE THREAD

**Issue by EdOverflow** [crypto101/crypto101.github.io#2]
www.crypto101.io uses HSTS, but doesn't have a redirection from HTTP on port 80 to HTTPS on port 443. As a result, clients who visit the plaintext host won't notice and activate HSTS. Since you are using Cloudflare all you have to do is set a page rule as follows:

1) Visit https://www.cloudflare.com/a/page-rules/PROJECTNAME;
2) Add `http://*.crypto101.io/*`;
3) Select "Always Use HTTPS"

**Comment by EdOverflow** [comment]
You clearly have the header set correctly, but just forgot to set up the redirect.

~~~
$ curl -i https://www.crypto101.io/ | grep Strict-Transport-Security
Strict-Transport-Security: max-age=15552000; preload
~~~

**Comment by EdOverflow** [comment]
@lvh Is this not the right place to submit issues?

**Comment by lvh** [comment]
Sorry, I just haven't been paying attention :) this is fixed. Thanks!
